a = ('item1', 'item2', '56', 'apples', 'bananas', ['balls','cats'])
print("a is a tuple now..")
print(a)
a = list(a)
print("a is a list now..")
#a[5:] = ('oranges',)
print(a)
a = tuple(a)
print(a)
print("a is a tuple again..")